import os
import json
from datetime import datetime
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
import google.generativeai as genai

class CrisisClassification(BaseModel):
    crisis_type: str
    severity: int
    affected_radius_km: float
    affected_population: int
    conflict_detected: bool
    conflict_description: str
    confidence: float
    reasoning_steps: List[str]

async def run_crisis_classifier(unified_signal: Dict[str, Any]) -> Dict[str, Any]:
    """
    Crisis Classifier Agent function.
    This agent takes the unified_signal from the Signal Fusion Agent and uses 
    Gemini to classify the crisis type, severity, radius, and affected population. 
    It specifically checks for conflicting signals.
    """
    trace = []
    
    def log_step(step: str):
        msg = f"[CRISIS_CLASSIFIER] [STEP] {step}"
        print(msg)
        trace.append(msg)
        
    log_step("Received incoming unified_signal data.")
    
    # Handle potentially empty or missing data
    if not unified_signal:
        log_step("WARNING: unified_signal is empty or missing.")
        
    log_step("Preparing to call Gemini to analyze and classify the crisis.")
    
    api_key = os.environ.get("GEMINI_API_KEY", os.environ.get("GOOGLE_API_KEY", ""))
    if not api_key:
        log_step("WARNING: GEMINI_API_KEY not found in environment. Call may fail.")
    genai.configure(api_key=api_key)
    
    system_instruction = """
    You are an expert Crisis Classifier Agent for a Pakistani city.
    Analyze the provided unified_signal (which includes social media analysis, weather, and traffic data).
    
    Your task is to:
    1. Classify the crisis_type strictly as one of: flood, heatwave, accident, infrastructure_failure, power_outage.
    2. Estimate severity from 1 (minor) to 5 (critical).
    3. Estimate affected_radius_km.
    4. Estimate affected_population (rough number).
    5. Give a confidence score (0-1).
    6. Provide reasoning_steps explaining each decision.
    7. CRITICALLY IMPORTANT: Check for conflicting signals. For example, if social posts say 'flood' but weather data shows zero rainfall and no humidity, or if another signal suggests a broken water main instead. 
    If a conflict is detected, set conflict_detected to true and explain it in conflict_description.
    """
    
    try:
        model = genai.GenerativeModel(
            model_name="gemini-2.0-flash",
            system_instruction=system_instruction
        )
        
        prompt = f"Analyze the following unified_signal and output a structured classification:\n{json.dumps(unified_signal, indent=2)}"
        
        log_step("Executing Gemini API call...")
        response = model.generate_content(
            prompt,
            generation_config=genai.GenerationConfig(
                response_mime_type="application/json",
                response_schema=CrisisClassification,
                temperature=0.2
            )
        )
        
        log_step("Successfully received classification from Gemini.")
        
        classification_data = json.loads(response.text)
        
        # Log reasoning steps generated by Gemini
        for r_step in classification_data.get("reasoning_steps", []):
            log_step(f"Gemini reasoning: {r_step}")
            
        if classification_data.get("conflict_detected"):
            log_step(f"Conflict detected by Gemini: {classification_data.get('conflict_description')}")
            
        # Parse the output into our Pydantic model structure
        result_obj = CrisisClassification(**classification_data)
        
    except Exception as e:
        log_step(f"Error calling Gemini API: {str(e)}")
        # Provide fallback behavior so the system doesn't crash during demo
        result_obj = CrisisClassification(
            crisis_type="unknown",
            severity=1,
            affected_radius_km=0.0,
            affected_population=0,
            conflict_detected=False,
            conflict_description="",
            confidence=0.0,
            reasoning_steps=["API call failed", "Returning fallback response"]
        )

    log_step("Formatting final response object.")
    
    return {
        "result": result_obj.dict(),
        "confidence": result_obj.confidence,
        "reasoning_steps": trace,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "agent_name": "CRISIS_CLASSIFIER"
    }
