import os
import json
from datetime import datetime
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
import google.generativeai as genai

class IncidentInfo(BaseModel):
    incident_id: str
    crisis_type: str
    severity: int
    affected_population: int
    location: str

class AllocatorRequest(BaseModel):
    incidents: List[IncidentInfo]
    available_resources: Dict[str, int]

class AllocationResult(BaseModel):
    allocation_plan: Dict[str, Dict[str, int]]
    trade_off_reasoning: str
    unmet_needs: List[str]
    reasoning_steps: List[str]

async def run_resource_allocator(incidents: List[Dict[str, Any]], available_resources: Dict[str, int]) -> Dict[str, Any]:
    """
    Resource Allocator Agent function.
    Takes a list of ongoing incidents and available emergency resources,
    and intelligently allocates them while explaining the trade-offs.
    """
    trace = []
    
    def log_step(step: str):
        msg = f"[RESOURCE_ALLOCATOR] [STEP] {step}"
        print(msg)
        trace.append(msg)
        
    log_step(f"Received {len(incidents)} incidents for resource allocation.")
    log_step(f"Available resources: {available_resources}")
    
    log_step("Preparing to call Gemini to determine optimal allocation plan.")
    
    api_key = os.environ.get("GEMINI_API_KEY", os.environ.get("GOOGLE_API_KEY", ""))
    if not api_key:
        log_step("WARNING: GEMINI_API_KEY not found in environment. Call may fail.")
    genai.configure(api_key=api_key)
    
    system_instruction = """
    You are an expert emergency response dispatcher.
    You are allocating scarce emergency resources across multiple simultaneous crises. 
    Show your reasoning step by step. Explain every trade-off. 
    Be specific about why each unit goes where.
    
    For your logic:
    1. Score each incident based on: severity * affected_population / response_urgency.
    2. Determine exactly how many units of each available resource go to which incident.
    3. If resources are insufficient, clearly flag which incidents are underserved in 'unmet_needs'.
    4. Provide the final assignment in 'allocation_plan', mapping incident_id to a dictionary of resource counts.
    """
    
    # Dump inputs to JSON for prompt
    input_data = {
        "incidents": incidents,
        "available_resources": available_resources
    }
    
    try:
        model = genai.GenerativeModel(
            model_name="gemini-2.0-flash",
            system_instruction=system_instruction
        )
        
        prompt = f"Analyze the following incidents and resources, and provide a structured allocation plan:\n{json.dumps(input_data, indent=2)}"
        
        log_step("Executing Gemini API call...")
        response = model.generate_content(
            prompt,
            generation_config=genai.GenerationConfig(
                response_mime_type="application/json",
                response_schema=AllocationResult,
                temperature=0.3
            )
        )
        
        log_step("Successfully received allocation plan from Gemini.")
        
        allocation_data = json.loads(response.text)
        
        # Log reasoning steps generated by Gemini
        for r_step in allocation_data.get("reasoning_steps", []):
            log_step(f"Gemini reasoning: {r_step}")
            
        result_obj = AllocationResult(**allocation_data)
        
    except Exception as e:
        log_step(f"Error calling Gemini API: {str(e)}")
        # Provide fallback behavior
        result_obj = AllocationResult(
            allocation_plan={},
            trade_off_reasoning=f"Fallback: API error occurred - {str(e)}",
            unmet_needs=["All incidents underserved due to API failure"],
            reasoning_steps=["API call failed", "Returning fallback response"]
        )

    log_step("Formatting final response object.")
    
    return {
        "result": result_obj.dict(),
        "confidence": 0.85, # Fixed confidence or could be parsed if added to schema
        "reasoning_steps": trace,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "agent_name": "RESOURCE_ALLOCATOR"
    }
