import os
import json
from datetime import datetime
from typing import List, Dict, Any
from pydantic import BaseModel
import google.generativeai as genai

class AnomalyOutput(BaseModel):
    detected_anomaly: bool
    anomaly_description: str
    confidence: float
    reasoning_steps: List[str]

class SignalResponse(BaseModel):
    result: Dict[str, Any]
    confidence_score: float
    reasoning_trace: List[str]
    timestamp: str

def score_post(post: str) -> Dict[str, float]:
    """
    Mock scoring function for a single social post.
    Evaluates credibility, urgency, and location match.
    """
    post_lower = post.lower()
    
    urgency = 0.5
    if any(word in post_lower for word in ["bhar gaya", "flooding", "emergency", "heavy", "phans gayi"]):
        urgency = 0.9
        
    location_match = 0.5
    if any(word in post_lower for word in ["g-10", "g-9", "g-11", "g10", "g9", "g11"]):
        location_match = 0.9
        
    credibility = 0.8  # Default high credibility for hackathon demo
    
    return {
        "text": post,
        "credibility": credibility,
        "urgency": urgency,
        "location_match": location_match
    }

async def run_signal_fusion(social_posts: List[str], weather: Dict[str, float], traffic: Dict[str, int]) -> Dict[str, Any]:
    """
    Signal Fusion Agent function.
    Combines social, weather, and traffic data, scores posts, 
    and leverages Gemini to identify potential anomalies.
    """
    trace = []
    
    def log_step(step: str):
        msg = f"[SIGNAL_FUSION] [STEP] {step}"
        print(msg)
        trace.append(msg)
        
    log_step("Received incoming signals: social, weather, traffic.")
    
    # 1. Score social posts
    log_step("Scoring social posts for credibility, urgency, and location match.")
    scored_posts = [score_post(post) for post in social_posts]
    
    # 2. Combine signals
    log_step("Fusing all signals into a unified_signal dictionary.")
    unified_signal = {
        "social_analysis": scored_posts,
        "weather_data": weather,
        "traffic_data": traffic
    }
    
    # 3. Analyze with Gemini
    log_step("Preparing to call Gemini 2.0 Flash to analyze unified signals.")
    
    # Ensure API key is configured
    api_key = os.environ.get("GEMINI_API_KEY", os.environ.get("GOOGLE_API_KEY", ""))
    if not api_key:
        log_step("WARNING: GEMINI_API_KEY not found in environment. Call may fail.")
    genai.configure(api_key=api_key)
    
    system_instruction = """
    You are a crisis signal analyst for a Pakistani city (e.g., Islamabad).
    Your job is to analyze incoming signals (social media posts, weather data, and traffic congestion)
    and determine if there is an ongoing crisis or anomaly.
    Output your analysis strictly in the requested JSON structure.
    """
    
    try:
        model = genai.GenerativeModel(
            model_name="gemini-2.0-flash",
            system_instruction=system_instruction
        )
        
        prompt = f"Analyze the following unified signals and determine if an anomaly is detected:\n{json.dumps(unified_signal, indent=2)}"
        
        log_step("Executing Gemini API call...")
        response = model.generate_content(
            prompt,
            generation_config=genai.GenerationConfig(
                response_mime_type="application/json",
                response_schema=AnomalyOutput,
                temperature=0.2
            )
        )
        
        log_step("Successfully received analysis from Gemini.")
        
        analysis_result = json.loads(response.text)
        
        # Log reasoning steps generated by Gemini
        for r_step in analysis_result.get("reasoning_steps", []):
            log_step(f"Gemini reasoning: {r_step}")
            
    except Exception as e:
        log_step(f"Error calling Gemini API: {str(e)}")
        # Provide fallback behavior so the system doesn't crash during demo
        analysis_result = {
            "detected_anomaly": True,
            "anomaly_description": f"Fallback: API error occurred - {str(e)}",
            "confidence": 0.0,
            "reasoning_steps": ["API call failed", "Returning fallback response"]
        }

    log_step("Formatting final response object.")
    
    return {
        "result": {
            "detected_anomaly": analysis_result.get("detected_anomaly", False),
            "anomaly_description": analysis_result.get("anomaly_description", ""),
            "unified_signal": unified_signal
        },
        "confidence": float(analysis_result.get("confidence", 0.0)),
        "reasoning_steps": trace,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "agent_name": "SIGNAL_FUSION"
    }
